### ISSUE TITLE
Add cvar to disable flag state icons on top of screen

### ISSUE THREAD

**Issue by ryvnf** [oatot/oatot#82]
I personally prefer to play with a simple HUD when playing. And I therefore think that the flag state icons in the upper left and upper right corners clutters the screen somewhat.

I think it would be nice to have an cvar to disable it, maybe called `cg_flagstatusStyle`, `cg_hudFlagStyle` or `cg_hudFlagstatusStyle`. That cvar could also then be used to add even more styles for the flag status, if that is desired in the future.

Currently I think something like `0` for vanilla baseoa style with no flags at top of screen, and `1` for what is currently being used.

**Comment by GuildDio** [comment]
That's good suggestion, thanks! :+1:
